const express=require("express");
const multer=require("multer");
const {TwitterApi}=require("twitter-api-v2");
const app=express(),upload=multer({dest:"/tmp",limits:{fileSize:512*1024*1024}});
app.use(express.urlencoded({extended:true}));
let verifier="",client=null;
const BASE=process.env.BASE_URL;
app.get("/",(_,res)=>res.send(`<!doctype html><meta name="viewport" content="width=device-width"><title>X Publisher</title><style>body{font-family:sans-serif;max-width:650px;margin:40px auto;padding:20px}button,input,textarea{font-size:18px;margin:8px 0;padding:12px;width:100%;box-sizing:border-box}button{background:#111;color:#fff;border:0;border-radius:10px}</style><h1>X Publisher</h1><p>동영상 업로드 → X 게시</p><a href="/login"><button>X 계정 연결</button></a><form action="/post" method="post" enctype="multipart/form-data"><input type="file" name="video" accept="video/*" required><textarea name="text" rows="5" maxlength="280" placeholder="게시 문구"></textarea><button>동영상 X에 게시</button></form>`));
app.get("/login",(_,res)=>{const c=new TwitterApi({clientId:process.env.X_CLIENT_ID,clientSecret:process.env.X_CLIENT_SECRET});const x=c.generateOAuth2AuthLink(BASE+"/callback",{scope:["tweet.read","tweet.write","users.read","offline.access"]});verifier=x.codeVerifier;res.redirect(x.url)});
app.get("/callback",async(req,res)=>{try{const c=new TwitterApi({clientId:process.env.X_CLIENT_ID,clientSecret:process.env.X_CLIENT_SECRET});const x=await c.loginWithOAuth2({code:req.query.code,codeVerifier:verifier,redirectUri:BASE+"/callback"});client=x.client;res.redirect("/")}catch(e){res.status(500).send("X 연결 실패: "+e.message)}});
app.post("/post",upload.single("video"),async(req,res)=>{try{if(!client)return res.status(401).send("먼저 X 계정을 연결하세요.");const id=await client.v1.uploadMedia(req.file.path,{mimeType:req.file.mimetype});const out=await client.v2.tweet({text:req.body.text||"",media:{media_ids:[id]}});res.send(`게시 완료<br><a href="https://x.com/i/web/status/${out.data.id}">X 게시물 열기</a>`)}catch(e){res.status(500).send("게시 실패: "+e.message)}});
app.get("/health",(_,r)=>r.send("ok"));app.listen(process.env.PORT||8080);